#! /usr/bin/osascript
#v1.3
on run arguments
	tell application "System Events"
		tell application "Script Editor"
			quit
		end tell
		tell application "open-stage-control"
			quit
		end tell
		tell application "MidiPipe"
			quit
		end tell

		delay 2

 	   tell application "Terminal"
 		   	set miniaturized of window 1 to true
 	   end tell

	end tell
end run