#! /usr/bin/osascript
#v1.0
on run arguments
	tell application "System Events"
		tell application "Script Editor"
			quit
		end tell
		tell application "open-stage-control"
			quit
		end tell
		tell application "MidiPipe"
			quit
		end tell
	end tell
	tell application "Terminal"
		activate
	end tell
end run